{
  imports = [
    ./browsers/firefox.nix
    ./communication/discord.nix
    ./communication/nheko.nix
    ./communication/quaternion.nix
    ./communication/teams.nix
    ./editors/openlens.nix
    ./editors/vscode.nix
    ./entertainment/osu.nix
    ./entertainment/prism.nix
    ./entertainment/r2modman.nix
    ./entertainment/runelite.nix
    ./entertainment/steam.nix
    ./graphics/blender.nix
    ./graphics/cura.nix
    ./graphics/unity.nix
    ./media/obs.nix
    ./media/spotify.nix
    ./productivity/libreoffice.nix
  ];
}
