{
  imports = [
    ./browsers/firefox.nix
    ./communication/cinny.nix
    ./communication/discord.nix
    ./communication/nheko.nix
    ./communication/quaternion.nix
    ./communication/teams.nix
    ./editors/ghidra.nix
    ./editors/openlens.nix
    ./editors/vscode.nix
    ./entertainment/osu.nix
    ./entertainment/prism.nix
    ./entertainment/r2modman.nix
    ./entertainment/runelite.nix
    ./entertainment/runescape.nix
    ./entertainment/steam.nix
    ./graphics/blender.nix
    ./graphics/cura.nix
    ./graphics/unity.nix
    ./media/mpv.nix
    ./media/obs.nix
    ./media/spotify.nix
    ./productivity/freecad.nix
    ./productivity/libreoffice.nix
    ./utility/nextcloud.nix
    ./utility/qbittorrent.nix
  ];
}
